### ISSUE TITLE
ModuleNotFoundError: No module named 'Vgamepad'

### ISSUE THREAD

**Issue by Hymandois** [1hubert/genshin-dialogue-autoskip#14]
\genshin-dialogue-autoskip-main\autoskip_dialogue.py", line 5, in <module>
    import vgamepad as vg
ModuleNotFoundError: No module named 'vgamepad'

Do I have to install a virtual controller or something?

**Comment by 1hubert** [comment]
As of now you have to install the vgamepad too, even if you're only going to use keyboard and mouse.

You can install all required modules with `pip install -r requirements.txt`

**Comment by Hymandois** [comment]
Do I do this through cmd as admin?

**Comment by 1hubert** [comment]
cmd or any other command line interface will work. Admin privileges are not strictly required.

If you're on windows, one way to install the modules is:
1) Open the `genshin-dialogue-autoskip` folder with File Explorer
2) In the search window of File Explorer type `cmd`
3) In that cmd, type `pip install -r requirements.txt`

Hope that helps!

**Comment by 1hubert** [comment]
Two issues that might hold you back:
- It seems like you run this command in `C:\WINDOWS\system32` and not `genshin-dialogue-autoskip`'s location (that's why I said to open the cmd from File Explorer
- If `pip` is not recognized, that probably means you don't have Python in your PATH

So I'd say, reinstall Python and make sure that the "add to PATH" checkbox is checked. Then install required modules by following the 3-step process I described earlier. GL!

**Comment by Hymandois** [comment]
I actually didnt do either, I did both now and it works, Thank you!
