### ISSUE TITLE
Merge controller branch into main

### ISSUE THREAD

**Issue by Livour** [1hubert/genshin-dialogue-autoskip#35]
Add the functionality of the controller branch into the main branch ,It's like 20 commits behind.

I could implement this myself but It says that the Controller branch's readme that it is still experimental (Not sure if Readme is up to date). If it's really is still experimental, what other tests/features does it need?

and btw, Is it supposed to work automatically when switching between keyboard/gamepad or do you need to update the `.env`?

**Comment by 1hubert** [comment]
Hey, Livour. I appreciate your concern, but I'd rather keep the gamepad functionality somewhere else than the main script, for three reasons:
- The code is easier to read. I want all people, even non-coders to be able to know what they're actually executing. 95%+ of people don't need gamepad support. They'd actually rather not have it.
- It's one less potential dependency issue.
- I want the main branch to be 100% test-able by me, and to be able to do it I'd have to own DS4 and Xbox gamepads which I don't have. I'm the main person answering github issues, so I want to know what I'm doing.

When xdenotte added Xbox gamepad support [here](https://github.com/1hubert/genshin-dialogue-autoskip/pull/9), he said *"there may be bugs, especially since I don’t know if DS4 works since because I don’t have it"*. That's the issue with gamepads. That's why I created a separate branch and labeled it as "Experimental" (might not be the semantically right word, but basically I meant "expect bugs").

Today, I've updated the [gamepad branch](https://github.com/1hubert/genshin-dialogue-autoskip/tree/gamepad_only) to basically the newest version of the main branch, but exclusively for gamepads. The ahead/behind commit count is not a meaningful measure, as those branches are not planned to be merged.

> and btw, Is it supposed to work automatically when switching between keyboard/gamepad or do you need to update the .env?

The gamepad branch is supposed to switch automatically between different gamepads, it doesn't support keyboard. The `.env` works in the exact same way as in the main branch; it stores screen dimensions.

I hope you understand <3

Have a nice day!
