### ISSUE TITLE
does skip dialogue but doesnt auto select the bottom option

### ISSUE THREAD

**Issue by MrOliverYt** [1hubert/genshin-dialogue-autoskip#36]
Hi, the mod works as intended, but it does not auto select the bottom response option.

Do you know what might be causing this? Thanks!

**Comment by mokahless** [comment]
I'm running into this issue at 4K, with a secondary monitor. It's inconsistent and works in some dialogue but not in others. Perhaps a difference in systems/latency that could be solved with the option of a less aggressively quick click? Not sure though because pausing and resuming the script still results in no option being pressed by the program.

If you want to try to reproduce it, the specific one I was having an issue with is when talking to the person right before talking with Yinger in the chef shop during farewell archaic lord quest. Speaking with Yinger after fetching the water bucket (the next dialogue to have clickable options) didn't have an issue.

The issued dialogue in quest did move the mouse directly where the second option was, however it didn't seem to click. Clicking myself without moving the mouse from that position selected it. It then refused to move the mouse or click for the next few options.

I know this is pretty difficult to troubleshoot and if no one else has issues it might be somehow limited to the one dialogue interaction, so not sure if much can be done or even if reproducing/testing is practical (especially since this quest is so far in and not repeatable to test).

(side-note, I double checked the requirements)
