### ISSUE TITLE
program not doing anything

### ISSUE THREAD

**Issue by 0withoutface0** [1hubert/genshin-dialogue-autoskip#43]
installed everything, started it up as admin, pressed f8 it printed RUNNING but its not doing anything. 

display resolution is correct 
```
WIDTH=3840
HEIGHT=1080
```
![kép](https://github.com/user-attachments/assets/92dfe0b2-4bc7-492d-ab14-45196b0cfb67)

any help is appreciated! ty

**Comment by IcyFoxe** [comment]
Need to run it as administrator (as mentioned in readme)

**Comment by rozenrade** [comment]
> Need to run it as administrator (as mentioned in readme)

how do you run a py file as admin lol

**Comment by 0withoutface0** [comment]
yeah ive done that. i can send a video too.

rozenrade ***@***.***> ezt írta (időpont: 2024. aug. 28.,
Sze, 22:34):

**Comment by 0withoutface0** [comment]
> > Need to run it as administrator (as mentioned in readme)
> 
> how do you run a py file as admin lol

open an elevated terminal and start it from there...

**Comment by rozenrade** [comment]
makes sense am dumb, thanks for clarifying. o7

**Comment by 1hubert** [comment]
@rozenrade @0withoutface0  There's a `run.bat` file which makes it easier to run as admin as you can just right-click it 😉

**Comment by 0withoutface0** [comment]
@1hubert i will make a video of the issue rq (i havent been playing for a few weeks now cuz i was busy). 
last time i tried it didnt work even if run as admin 
i will report back in a few mins

**Comment by 1hubert** [comment]
@0withoutface0 No need for the video, I was just about to tell you -- The issue is the script's side, not yours. Basically your screen resolution makes it so the skip button is in an "unexpected" place, as the script is dumb and assumes that the skip button's position will be on the same relative x and y position as it is in 1920x1080.

**Comment by 1hubert** [comment]
I don't know an easy fix to this, and due to IRL stuff and me no longer playing Genshin Impact, I'm no longer able to solve every single issue people might have. Sorry. If someone else wants to help I'll review & merge their PR ASAP.

The placement of the skip button is hard to predict between different non-1080p resolutions, so I was thinking of the following solution:
1) The first time you run the script, instead of asking for your screen resolution, it's going to ask you to switch tabs to Genshin Impact, talk to some NPC and click F9 to take a screenshot.
2) Some kind of simple vision AI could try to find the exact coordinates of the skip button, looking for places resembling an image of it which would be included in the repo.
3) Same with the bottom dialogue option (based on an image of the dialogue bubble)
4) Instead of saving `WIDTH` and `HEIGHT` in `.env`, save the two above coordinates, and use them in the future.

**Comment by 0withoutface0** [comment]
ohhh i see! @1hubert 
i will add fixes for a few aspect ratios i can think of. (when i have time i will upload them here for merge)
i want to stay at a minimal effort solution.
thank you for explaining

**Comment by 0withoutface0** [comment]
Created a pull request. If there is any problem with the code let me know.
