### ISSUE TITLE
xbox gamepad support

### ISSUE THREAD

**Issue by xdenotte** [1hubert/genshin-dialogue-autoskip#8]
Hello!, I would like to know if support for xbox-like gamepads is possible, because the script does not work quite correctly, it does not skip dialogs, and at the stage of choosing an answer, the script moves the options up and down. Perhaps I'm doing something wrong?

**Comment by 1hubert** [comment]
Hello xdenotte!

In short, there is no support for xbox-like gamepads and you'd have to code it yourself because I don't own any gamepad controllers. 

If you're interested in adding the xbox controller support yourself, here's some info:
- One of our contributors vlsido has added support for a DualShock4 controller using a python library called vgamepad. You can learn more about vgamepad here: https://pypi.org/project/vgamepad/
- As it states on the library's website, respective classes for simulating DS4 and Xbox gamepads are: `VDS4Gamepad` and `VX360Gamepad`. You can see the `VDS4Gamepad` class in autoskip_dialogue.py.
- You could use a search engine or an AI chatbot for example solutions for emulating an Xbox controller using the `VX360Gamepad` in a similar way that our contributor vlsido did with VDS4Gamepad.

Have a nice day!

**Comment by xdenotte** [comment]
ok, I will try
